/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PCHardwareSpecialists.view;

import PCHardwareSpecialists.controller.BrandController;
import PCHardwareSpecialists.controller.BrandItemDetailsController;
import PCHardwareSpecialists.controller.IdGen;
import PCHardwareSpecialists.controller.ItemController;
import PCHardwareSpecialists.controller.OtherSql;
import PCHardwareSpecialists.controller.WarrentyController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import PCHardwareSpecialists.model.Brand;
import PCHardwareSpecialists.model.BrandItemDetails;
import PCHardwareSpecialists.model.Item;
import PCHardwareSpecialists.model.Warrenty;
import PCHardwareSpecialists.view.NewSupplyOrder;
import java.awt.Frame;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Hasithakn
 */
public class NewItem extends javax.swing.JInternalFrame {

    NewSupplyOrder nso = null;

    /**
     * Creates new form ViewCustomer
     */
    public NewItem() {
        initComponents();

        //biid id gen
        try {
            biidText.setText(IdGen.getNextId("branditemdetails", "biid", "BIID"));
        } catch (SQLException ex) {
            Logger.getLogger(NewItem.class.getName()).log(Level.SEVERE, null, ex);
        }

        ///combo fill
        fillitemDesCombo();
        fillbrandCombo();
        fillwarrentyPeriodCombo();
        ///table fill

        //searchable combos
        AutoCompleteDecorator.decorate(itemDescriptionCombo);
        AutoCompleteDecorator.decorate(brandCombo);
        AutoCompleteDecorator.decorate(warrentyPeriodCombo);
    }

    public NewItem(NewSupplyOrder a) {
        initComponents();
        nso = a;
        //biid id gen
        try {
            biidText.setText(IdGen.getNextId("branditemdetails", "biid", "BIID"));
        } catch (SQLException ex) {
            Logger.getLogger(NewItem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            Logger.getLogger(NewItem.class.getName()).log(Level.SEVERE, null, ex);
        }

        ///combo fill
        fillitemDesCombo();
        fillbrandCombo();
        fillwarrentyPeriodCombo();
        ///table fill

        //searchable combos
        AutoCompleteDecorator.decorate(itemDescriptionCombo);
        AutoCompleteDecorator.decorate(brandCombo);
        AutoCompleteDecorator.decorate(warrentyPeriodCombo);
    }

    public void fillitemDesCombo() {
        ArrayList<Item> item = null;
        try {
            item = ItemController.getAllItem();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(NewItem.this, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(NewItem.this, ex.getMessage());
        }
        itemDescriptionCombo.removeAllItems();
        for (Item item1 : item) {
            itemDescriptionCombo.addItem(item1.getDescription());
        }
    }

    public void fillbrandCombo() {
        ArrayList<Brand> brand = null;
        try {
            brand = BrandController.getAllBrand();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(NewItem.this, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(NewItem.this, ex.getMessage());
        }
        brandCombo.removeAllItems();
        for (Brand brand1 : brand) {
            brandCombo.addItem(brand1.getBrandName());
        }
    }

    public void fillwarrentyPeriodCombo() {
        ArrayList<Warrenty> warrenty = null;
        try {
            warrenty = WarrentyController.getAllWarrenty();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(NewItem.this, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(NewItem.this, ex.getMessage());
        }
        warrentyPeriodCombo.removeAllItems();
        for (Warrenty warrenty1 : warrenty) {
            warrentyPeriodCombo.addItem(warrenty1.getwPeriod());
        }
        try {
            warrentyPeriodCombo.setSelectedIndex(0);
        } catch (IllegalArgumentException e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        itemDescriptionCombo = new javax.swing.JComboBox();
        itemCodeText = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        brandCombo = new javax.swing.JComboBox();
        brandIdText = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        warrentyPeriodCombo = new javax.swing.JComboBox();
        widText = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        biidText = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        itemDesText = new javax.swing.JTextField();
        newItemButton = new javax.swing.JButton();
        warrentyPeriodText = new javax.swing.JTextField();
        newBrandButton = new javax.swing.JButton();
        brandText = new javax.swing.JTextField();
        newWarrentyButton = new javax.swing.JButton();
        newWarrentyButton1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        sellingPriceText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Item");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New Item");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Item"));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel20.setText("Item Code");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel21.setText("Item Description");

        itemDescriptionCombo.setEditable(true);
        itemDescriptionCombo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        itemDescriptionCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDescriptionComboActionPerformed(evt);
            }
        });

        itemCodeText.setEditable(false);
        itemCodeText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel22.setText("Brand");

        brandCombo.setEditable(true);
        brandCombo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        brandCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandComboActionPerformed(evt);
            }
        });

        brandIdText.setEditable(false);
        brandIdText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel23.setText("Brand ID");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel24.setText("Warrenty Period");

        warrentyPeriodCombo.setEditable(true);
        warrentyPeriodCombo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        warrentyPeriodCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warrentyPeriodComboActionPerformed(evt);
            }
        });

        widText.setEditable(false);
        widText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel25.setText("WID");

        biidText.setEditable(false);
        biidText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel26.setText("BIID");

        addButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        addButton.setText("ADD New");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        itemDesText.setEditable(false);
        itemDesText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        newItemButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        newItemButton.setText("New Item Des.");
        newItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newItemButtonActionPerformed(evt);
            }
        });

        warrentyPeriodText.setEditable(false);
        warrentyPeriodText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        newBrandButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        newBrandButton.setText("New Brand");
        newBrandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBrandButtonActionPerformed(evt);
            }
        });

        brandText.setEditable(false);
        brandText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        newWarrentyButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        newWarrentyButton.setText("New Warrenty");
        newWarrentyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWarrentyButtonActionPerformed(evt);
            }
        });

        newWarrentyButton1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        newWarrentyButton1.setText("Cancel");
        newWarrentyButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWarrentyButton1ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel27.setText("Selling Price");

        sellingPriceText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24))
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(itemDesText)
                            .addComponent(warrentyPeriodCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 332, Short.MAX_VALUE)
                            .addComponent(brandCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(itemDescriptionCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(warrentyPeriodText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brandText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(brandIdText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(newBrandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(itemCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(newItemButton))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(widText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newWarrentyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(sellingPriceText, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(biidText, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addButton)
                        .addGap(18, 18, 18)
                        .addComponent(newWarrentyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemDescriptionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newItemButton)
                    .addComponent(jLabel20)
                    .addComponent(itemCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemDesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBrandButton)
                    .addComponent(brandIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(warrentyPeriodCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(widText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newWarrentyButton)
                    .addComponent(jLabel25))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(warrentyPeriodText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sellingPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel27))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(biidText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(newWarrentyButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemDescriptionComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDescriptionComboActionPerformed
        //fill icode text
        String description = itemDescriptionCombo.getEditor().getItem().toString();
        ArrayList<Item> item = null;
        try {
            item = ItemController.searchItemByname(description);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(NewItem.this, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(NewItem.this, ex.getMessage());
        }
        try {
            itemCodeText.setText(item.get(0).getiCode());
            //fill itemDes text
            itemDesText.setText(item.get(0).getDescription());
        } catch (IndexOutOfBoundsException e) {
        }


    }//GEN-LAST:event_itemDescriptionComboActionPerformed

    private void brandComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandComboActionPerformed

        //fill bid text
        String brand = brandCombo.getEditor().getItem().toString();
        ArrayList<Brand> brand2 = null;
        try {
            brand2 = BrandController.searchBrandByName(brand);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(NewItem.this, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(NewItem.this, ex.getMessage());
        }
        try {
            if (!brandCombo.getEditor().getItem().toString().isEmpty()) {
                brandIdText.setText(brand2.get(0).getBid());
                brandText.setText(brand2.get(0).getBrandName());
            }

        } catch (IndexOutOfBoundsException e) {
        }

    }//GEN-LAST:event_brandComboActionPerformed

    private void warrentyPeriodComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warrentyPeriodComboActionPerformed
        //fill wid text
        String warrenty = warrentyPeriodCombo.getEditor().getItem().toString();
        ArrayList<Warrenty> warrenty2 = null;
        try {
            warrenty2 = WarrentyController.searchWarrentyByName(warrenty);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(NewItem.this, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(NewItem.this, ex.getMessage());
        }
        try {
            if (!warrentyPeriodCombo.getEditor().getItem().toString().isEmpty()) {
                widText.setText(warrenty2.get(0).getWid());
                warrentyPeriodText.setText(warrenty2.get(0).getwPeriod());
            }
        } catch (IndexOutOfBoundsException e) {

        }
    }//GEN-LAST:event_warrentyPeriodComboActionPerformed

    private void newItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newItemButtonActionPerformed

        String a = JOptionPane.showInputDialog(NewItem.this, "Enter Item Name .");
        if (!a.isEmpty()) {
            itemDescriptionCombo.getEditor().setItem("");
//                itemDescriptionCombo.setEnabled(false);
            itemDesText.setText(a);
            itemCodeText.setText("");
            try {
                itemCodeText.setText(IdGen.getNextId("item", "iCode", "I"));
            } catch (SQLException ex) {
                Logger.getLogger(NewItem.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
        }


    }//GEN-LAST:event_newItemButtonActionPerformed

    private void newBrandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBrandButtonActionPerformed

        String a = JOptionPane.showInputDialog(NewItem.this, "Enter Brand Name .");
        if (!a.isEmpty()) {
            brandCombo.getEditor().setItem("");
            //brandCombo.setEnabled(false);
            brandText.setText(a);
            brandIdText.setText("");
            try {
                brandIdText.setText(IdGen.getNextId("brand", "bid", "B"));
            } catch (SQLException ex) {
                Logger.getLogger(NewItem.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
        }


    }//GEN-LAST:event_newBrandButtonActionPerformed

    private void newWarrentyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWarrentyButtonActionPerformed

        String b = JOptionPane.showInputDialog(NewItem.this, "Enter Warrenty Period");
        if (!b.isEmpty()) {
            warrentyPeriodCombo.getEditor().setItem("");
            //warrentyDesCombo.setEnabled(false);              
            warrentyPeriodText.setText(b);
            try {
                widText.setText(IdGen.getNextId("warrenty", "wid", "W"));

            } catch (SQLException ex) {
                Logger.getLogger(NewItem.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
        }


    }//GEN-LAST:event_newWarrentyButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try {
            if (!widText.getText().isEmpty() && !brandIdText.getText().isEmpty() && !itemCodeText.getText().isEmpty() && !sellingPriceText.getText().isEmpty() && !biidText.getText().isEmpty() && !itemDesText.getText().isEmpty() && !brandText.getText().isEmpty() && !warrentyPeriodText.getText().isEmpty()) {
                Item item = new Item(itemCodeText.getText(), itemDesText.getText());
                Brand brand = new Brand(brandIdText.getText(), brandText.getText());
                Warrenty warrenty = new Warrenty(widText.getText(), warrentyPeriodText.getText());
                BrandItemDetails brandItemDetail = new BrandItemDetails(biidText.getText(), widText.getText(), brandIdText.getText(), itemCodeText.getText(), Double.parseDouble(sellingPriceText.getText()), item, brand, warrenty);
                int a = 0;
                try {
                    a = BrandItemDetailsController.addBrandItemDetailsAll(brandItemDetail);
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(NewItem.this, ex.getMessage());
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(NewItem.this, ex.getMessage());
                }
                if (a > 0) {
                    JOptionPane.showMessageDialog(NewItem.this, "Item Added");
                    //combo fill
                    if (nso != null) {
                        nso.fillItemDesCombo();
                        nso.fillbrandComboByItem();
                        nso.fillwarrentyDesCombo();
                        nso.fillwarrentyDesComboByBrand();
                        nso.iCodeText.setText(itemCodeText.getText());
                        nso.brandIdText.setText(brandIdText.getText());
                        nso.widText.setText(widText.getText());
                        nso.itemDesCombo.getEditor().setItem(itemDesText.getText());
                        nso.brandNameCombo.getEditor().setItem(brandText.getText());
                        nso.warrentyperiodCombo.getEditor().setItem(warrentyPeriodText.getText());
                    } else {
                    }

                    fillitemDesCombo();
                    fillbrandCombo();
                    fillwarrentyPeriodCombo();
                    //biid id gen
                    try {
                        biidText.setText(IdGen.getNextId("branditemdetails", "biid", "BIID"));
                    } catch (SQLException ex) {
                        Logger.getLogger(NewItem.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(NewItem.this, "Item Adding Failed");
                }
            } else {
                JOptionPane.showMessageDialog(NewItem.this, "Please Enter Valid Details");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(NewItem.this, "Error");
            Logger.getLogger(NewItem.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_addButtonActionPerformed

    private void newWarrentyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWarrentyButton1ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_newWarrentyButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField biidText;
    private javax.swing.JComboBox brandCombo;
    private javax.swing.JTextField brandIdText;
    private javax.swing.JTextField brandText;
    private javax.swing.JTextField itemCodeText;
    private javax.swing.JTextField itemDesText;
    private javax.swing.JComboBox itemDescriptionCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton newBrandButton;
    private javax.swing.JButton newItemButton;
    private javax.swing.JButton newWarrentyButton;
    private javax.swing.JButton newWarrentyButton1;
    private javax.swing.JTextField sellingPriceText;
    private javax.swing.JComboBox warrentyPeriodCombo;
    private javax.swing.JTextField warrentyPeriodText;
    private javax.swing.JTextField widText;
    // End of variables declaration//GEN-END:variables
}
