/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PCHardwareSpecialists.view;

import PCHardwareSpecialists.controller.IdGen;
import PCHardwareSpecialists.controller.OChequeController;
import PCHardwareSpecialists.controller.OrderPaymentsController;
import PCHardwareSpecialists.model.OCheque;
import PCHardwareSpecialists.model.OrderPayments;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hasithakn
 */
public class NewOrderPayment extends javax.swing.JFrame {

    ViewOrderPayments vop = null;
    ViewOrderPaymentByOid vopbo = null;

    /**
     * Creates new form NewOrderPayment
     */
    public NewOrderPayment() {
        initComponents();
        String a = "";
        try {
            a = IdGen.getNextId("orderpayments", "opid", "OPID");
        } catch (SQLException ex) {
            Logger.getLogger(NewOrderPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
        pidText.setText(a);
        buttonGroup1.add(cashCheck);
        buttonGroup1.add(chequecheck);
    }

    public NewOrderPayment(ViewOrderPayments vop) {
        initComponents();
        this.vop = vop;
        String a = "";
        try {
            a = IdGen.getNextId("orderpayments", "opid", "OPID");
        } catch (SQLException ex) {
            Logger.getLogger(NewOrderPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
        pidText.setText(a);
        buttonGroup1.add(cashCheck);
        buttonGroup1.add(chequecheck);
    }

    public NewOrderPayment(ViewOrderPaymentByOid vopbo) {
        initComponents();
        this.vopbo = vopbo;
        String a = "";
        try {
            a = IdGen.getNextId("orderpayments", "opid", "OPID");
        } catch (SQLException ex) {
            Logger.getLogger(NewOrderPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
        pidText.setText(a);
        buttonGroup1.add(cashCheck);
        buttonGroup1.add(chequecheck);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        amountText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        oidText = new javax.swing.JTextField();
        pidText = new javax.swing.JTextField();
        cashCheck = new javax.swing.JCheckBox();
        chequecheck = new javax.swing.JCheckBox();
        datePicker = new org.jdesktop.swingx.JXDatePicker();
        chequeNoText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New Order Payment");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setText("Payment ID");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Order ID");

        amountText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("Amount");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton3.setText("ADD New");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        oidText.setEditable(false);
        oidText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        pidText.setEditable(false);
        pidText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        cashCheck.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cashCheck.setSelected(true);
        cashCheck.setText("By Cash");
        cashCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashCheckActionPerformed(evt);
            }
        });

        chequecheck.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        chequecheck.setText("By Cheque");
        chequecheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chequecheckActionPerformed(evt);
            }
        });

        chequeNoText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        chequeNoText.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(oidText, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pidText, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 3, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cashCheck)
                                            .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 186, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(chequecheck)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chequeNoText))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(oidText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pidText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cashCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chequecheck)
                            .addComponent(chequeNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            if (cashCheck.isSelected()) {
                int a = 0;
                OrderPayments op = new OrderPayments(pidText.getText(), oidText.getText(), Double.parseDouble(amountText.getText()), datePicker.getDate());
                try {
                    a = OrderPaymentsController.addOrderPayment(op);
                } catch (SQLException ex) {
                    Logger.getLogger(NewOrderPayment.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(NewOrderPayment.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (a > 0) {
                    if (vop != null) {
                        vop.fillTable();
                    }
                    if (vopbo != null) {
                        vopbo.fillTable();
                        vopbo.getDetails();
                    }
                    this.dispose();
                    JOptionPane.showMessageDialog(NewOrderPayment.this, "Payment Added");

                } else {
                    JOptionPane.showMessageDialog(NewOrderPayment.this, "Payment Adding Faild");
                }
            } else {
                int a = 0;
                int b = 0;
                OrderPayments op = new OrderPayments(pidText.getText(), oidText.getText(), Double.parseDouble(amountText.getText()), datePicker.getDate());
                OCheque oc = new OCheque(pidText.getText(), chequeNoText.getText());
                try {
                    a = OrderPaymentsController.addOrderPaymentCheque(op, oc);
                } catch (SQLException ex) {
                    Logger.getLogger(NewOrderPayment.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(NewOrderPayment.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (a > 0) {
                    if (vop != null) {
                        vop.fillTable();
                    }
                    if (vopbo != null) {
                        vopbo.fillTable();
                        vopbo.getDetails();
                    }
                    JOptionPane.showMessageDialog(NewOrderPayment.this, "Payment Added");

                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(NewOrderPayment.this, "Payment Adding Faild");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(NewOrderPayment.this, "Payment Adding Faild");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void cashCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashCheckActionPerformed
        chequeNoText.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_cashCheckActionPerformed

    private void chequecheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chequecheckActionPerformed
        chequeNoText.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_chequecheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewOrderPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewOrderPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewOrderPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewOrderPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewOrderPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cashCheck;
    private javax.swing.JTextField chequeNoText;
    private javax.swing.JCheckBox chequecheck;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField oidText;
    private javax.swing.JTextField pidText;
    // End of variables declaration//GEN-END:variables
}
