/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PCHardwareSpecialists.view;

import PCHardwareSpecialists.controller.ComboSearch;
import PCHardwareSpecialists.controller.CustomerController;
import PCHardwareSpecialists.controller.IdGen;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import PCHardwareSpecialists.model.Customer;
import java.awt.Frame;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Hasithakn
 */
public class ViewCustomer extends javax.swing.JInternalFrame {

    Invoice i = null;

    /**
     * Creates new form ViewCustomer
     */
    public ViewCustomer() {
        initComponents();
        setTitle("Customers");
        nicc.setVisible(false);
        addcancelButton.setVisible(false);

        ArrayList<Customer> customerList = null;
        try {
            customerList = CustomerController.getAllCustomer();

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
        }
        DefaultTableModel dtm = (DefaultTableModel) customerTable.getModel();
        dtm.setRowCount(0);
        for (Customer customer : customerList) {
            customerCombo.addItem(customer.getCustName());
            Object[] rowData = {customer.getCustId(), customer.getNic(), customer.getCustName(), customer.getTel(), customer.getCustEmail(), customer.getAddress()};
            dtm.addRow(rowData);
            AutoCompleteDecorator.decorate(customerCombo);
            //new ComboSearch().setSearchableComboBox(customerCombo, "No Customer Found..");
        }
        ListSelectionModel selectionModel = customerTable.getSelectionModel();
        selectionModel.setSelectionInterval(0, 0);

    }

    public ViewCustomer(Invoice i) {
        initComponents();
        this.i = i;
        setTitle("Customers");
        nicc.setVisible(false);
        addcancelButton.setVisible(false);

        ArrayList<Customer> customerList = null;
        try {
            customerList = CustomerController.getAllCustomer();

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
        }
        DefaultTableModel dtm = (DefaultTableModel) customerTable.getModel();
        dtm.setRowCount(0);
        for (Customer customer : customerList) {
            customerCombo.addItem(customer.getCustName());
            Object[] rowData = {customer.getCustId(), customer.getNic(), customer.getCustName(), customer.getTel(), customer.getCustEmail(), customer.getAddress()};
            dtm.addRow(rowData);
            AutoCompleteDecorator.decorate(customerCombo);
            //new ComboSearch().setSearchableComboBox(customerCombo, "No Customer Found..");
        }
        ListSelectionModel selectionModel = customerTable.getSelectionModel();
        selectionModel.setSelectionInterval(0, 0);

    }

    public void checkTextBoxes() {
        /*if (customerCombo.getSelectedItem() != null) {
         if (customerCombo.getSelectedItem().toString().isEmpty() || custIdText.getText().isEmpty() || custEmailText.getText().isEmpty() || nicCombo.getSelectedItem().toString().isEmpty() || addressText.getText().isEmpty() || telText.getText().isEmpty() || activeAdd == false) {
         addButton.setEnabled(false);

         } else {
         addButton.setEnabled(true);
         }
         } else {
         addButton.setEnabled(false);
         }*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        custIdText = new javax.swing.JTextField();
        addressText = new javax.swing.JTextField();
        custEmailText = new javax.swing.JTextField();
        telText = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        customerCombo = new javax.swing.JComboBox();
        newButton = new javax.swing.JButton();
        nicCombo = new javax.swing.JComboBox();
        nicc = new javax.swing.JLabel();
        addcancelButton = new javax.swing.JButton();
        custCountText = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customers");

        customerTable.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "NIC", "Customer ", "Contact No.", "Email", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        customerTable.getTableHeader().setReorderingAllowed(false);
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                customerTableMouseReleased(evt);
            }
        });
        customerTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customerTableKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                customerTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(customerTable);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer Details"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Customer ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Customer Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Customer Address");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Customer Nic");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Customer Email");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Customer Contact No.");

        custIdText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        custIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custIdTextActionPerformed(evt);
            }
        });
        custIdText.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                custIdTextPropertyChange(evt);
            }
        });
        custIdText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                custIdTextKeyReleased(evt);
            }
        });

        addressText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextActionPerformed(evt);
            }
        });
        addressText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressTextKeyReleased(evt);
            }
        });

        custEmailText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        custEmailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custEmailTextActionPerformed(evt);
            }
        });
        custEmailText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                custEmailTextKeyReleased(evt);
            }
        });

        telText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        telText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telTextActionPerformed(evt);
            }
        });
        telText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telTextKeyReleased(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        addButton.setText("ADD New");
        addButton.setEnabled(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        customerCombo.setEditable(true);
        customerCombo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        customerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerComboActionPerformed(evt);
            }
        });
        customerCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                customerComboKeyReleased(evt);
            }
        });

        newButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        nicCombo.setEditable(true);
        nicCombo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        nicCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicComboActionPerformed(evt);
            }
        });
        nicCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicComboKeyReleased(evt);
            }
        });

        nicc.setBackground(new java.awt.Color(255, 51, 51));
        nicc.setOpaque(true);

        addcancelButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        addcancelButton.setText("Cancel");
        addcancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(custIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nicCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nicc, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custCountText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(337, 337, 337))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(addcancelButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addButton))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(customerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(newButton)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(custEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(telText, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(customerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nicc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(custIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(nicCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(custCountText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(custEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(telText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton)
                    .addComponent(addcancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        deleteButton.setText("Delete Selected");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        updateButton.setText("Save Changes");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 956, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(deleteButton)
                    .addComponent(updateButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void custEmailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custEmailTextActionPerformed
        checkTextBoxes();        // TODO add your handling code here:
    }//GEN-LAST:event_custEmailTextActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void customerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerComboActionPerformed

        // addButton.setEnabled(false);
        checkTextBoxes();
//        nicCombo.addItem("");
//        addressText.setText("");
//        custEmailText.setText("");
//        telText.setText("");
//        nicCombo.addItem("");
        //addressText.setEditable(false);
        //custEmailText.setEditable(false);
        //telText.setEditable(false);

        telText.setForeground(Color.BLACK);
        ArrayList<Customer> customerlist = null;
        final JTextField textField = (JTextField) customerCombo.getEditor().getEditorComponent();
        String a = textField.getText();
        if (!a.isEmpty()) {
            try {
                customerlist = CustomerController.searchCustomerByName(a);
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
            }
            Customer[] customer = new Customer[customerlist.size()];
            for (int i = 0; i < customerlist.size(); i++) {
                customer[i] = customerlist.get(i);
            }
            if (customerlist.size() == 1 && customer != null) {
                nicCombo.removeAllItems();
                custIdText.setText(customer[0].getCustId());
                nicCombo.addItem(customer[0].getNic());
                addressText.setText(customer[0].getAddress());
                custEmailText.setText(customer[0].getCustEmail());
                telText.setText(Integer.toString(customer[0].getTel()));
                custCountText.setText(customerlist.size() + " Customers");
                int a1 = customerTable.getRowCount();
                int b = 0;
                String text = custIdText.getText();
                for (int i = 0; i < a1; i++) {
                    if (customerTable.getValueAt(i, 0).toString().equals(text)) {
                        break;
                    } else {
                        b++;
                    }
                }
                ListSelectionModel selectionModel = customerTable.getSelectionModel();
                selectionModel.setSelectionInterval(0, b);

            } else {
                nicCombo.removeAllItems();
                for (int i = 0; i < customerlist.size(); i++) {
                    nicCombo.addItem(customer[i].getNic());
                }
                custCountText.setText(customerlist.size() + " Customers");

            }
        }

    }//GEN-LAST:event_customerComboActionPerformed

    private void custIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custIdTextActionPerformed
        checkTextBoxes();        // TODO add your handling code here:
    }//GEN-LAST:event_custIdTextActionPerformed

    private void addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextActionPerformed
        checkTextBoxes();        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextActionPerformed

    private void telTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telTextActionPerformed
        checkTextBoxes();        // TODO add your handling code here:
    }//GEN-LAST:event_telTextActionPerformed

    private void customerComboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerComboKeyReleased
        //checkTextBoxes();
    }//GEN-LAST:event_customerComboKeyReleased

    private void custIdTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_custIdTextKeyReleased
        checkTextBoxes();        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_custIdTextKeyReleased

    private void addressTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTextKeyReleased
        checkTextBoxes();        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextKeyReleased

    private void custEmailTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_custEmailTextKeyReleased
        checkTextBoxes();

    }//GEN-LAST:event_custEmailTextKeyReleased

    private void telTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telTextKeyReleased
        checkTextBoxes();
        String text = telText.getText();

        if (text.length() > 0) {
            if (text.matches("0[1-9][1-8][0-9]{7}") || text.matches("[1-9][1-8][0-9]{7}")) {
                telText.setForeground(Color.BLACK);
            } else {
                telText.setForeground(Color.red);
            }
        } else {
            telText.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_telTextKeyReleased

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed

        String genaratedId = null;
        customerCombo.setEnabled(false);
        customerCombo.removeAllItems();
        String a = JOptionPane.showInputDialog(ViewCustomer.this, "Customer Name");
        customerCombo.getEditor().setItem(a);
        addcancelButton.setVisible(true);
        try {
            genaratedId = IdGen.getNextId("customer", "custId", "C");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
        }
        nicCombo.removeAllItems();
        addButton.setEnabled(true);
        custIdText.setText(genaratedId);
//        nicCombo.addItem("");
//        addressText.setText("");
//        custEmailText.setText("");
//        telText.setText("");
//        nicCombo.addItem("");
        addressText.setEditable(true);
        custEmailText.setEditable(true);
        telText.setEditable(true);
        //nicCombo.setEditable(true);
    }//GEN-LAST:event_newButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try {
            if (telText.getForeground() == Color.RED || nicc.isShowing() == true || nicCombo.getEditor().getItem().toString().isEmpty() || telText.getText().isEmpty() || custEmailText.getText().isEmpty() || addressText.getText().isEmpty()) {
                JOptionPane.showMessageDialog(ViewCustomer.this, "Please Enter Valid Details");
            } else {
                Customer customer = new Customer(custIdText.getText(), customerCombo.getEditor().getItem().toString(), nicCombo.getSelectedItem().toString(), addressText.getText(), custEmailText.getText(), Integer.parseInt(telText.getText()));
                try {
                    int a = CustomerController.addCustomer(customer);
                    if (a > 0) {
                        JOptionPane.showMessageDialog(ViewCustomer.this, "Customer Added");
                        addcancelButton.setVisible(false);
                        addButton.setEnabled(false);
//                    addressText.setEditable(false);
//                    custEmailText.setEditable(false);
//                    telText.setEditable(false);
                        //nicCombo.setEditable(false);
                        customerCombo.setEnabled(true);
                        ArrayList<Customer> customerList = null;
                        try {
                            customerList = CustomerController.getAllCustomer();
                        } catch (ClassNotFoundException ex) {
                            JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
                        }
                        DefaultTableModel dtm = (DefaultTableModel) customerTable.getModel();
                        dtm.setRowCount(0);
                        customerCombo.removeAllItems();
                        for (Customer customer1 : customerList) {
                            customerCombo.addItem(customer1.getCustName());
                            Object[] rowData = {customer1.getCustId(), customer1.getNic(), customer1.getCustName(), customer1.getTel(), customer1.getCustEmail(), customer1.getAddress()};
                            dtm.addRow(rowData);
                            //new ComboSearch().setSearchableComboBox(customerCombo, "No Customer Found..");
                        }
                        if (i != null) {
                            i.customerIdCombo.getEditor().setItem(custIdText.getText());
                            i.fillCustomerDetailsById();
                        }
//                        for (Frame frame : Frame.getFrames()) {
//                            if (frame.getTitle().equals("Invoice")) {
//                                /* Cast to ChildJFrame */
//                                Invoice frameyo = (Invoice) frame;
//                                frameyo.customerIdCombo.getEditor().setItem(custIdText.getText());
//                                frameyo.fillCustomerDetailsById();
//                            }
//                        }
                    } else {
                        JOptionPane.showMessageDialog(ViewCustomer.this, "Customer Adding Faild");
                        ArrayList<Customer> customerList = null;
                        try {
                            customerList = CustomerController.getAllCustomer();
                        } catch (ClassNotFoundException ex) {
                            JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
                        }
                        customerCombo.removeAllItems();
                        for (Customer customer1 : customerList) {
                            customerCombo.addItem(customer1.getCustName());
                            //new ComboSearch().setSearchableComboBox(customerCombo, "No Customer Found..");
                        }
                    }
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(ViewCustomer.this, "Error .");
        }

    }//GEN-LAST:event_addButtonActionPerformed

    private void nicComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicComboActionPerformed
        //addButton.setEnabled(false);
        checkTextBoxes();
        final JTextField text1 = (JTextField) nicCombo.getEditor().getEditorComponent();
        String text = (String) text1.getText();
        if (text.length() > 0) {
            if (text.matches("[0-9]{9}[vV]")) {
                nicCombo.setForeground(Color.BLACK);
                nicc.setVisible(false);
            } else {
                nicCombo.setForeground(Color.red);
                nicc.setVisible(true);
            }
        } else {
            nicCombo.setForeground(Color.BLACK);
            nicc.setVisible(false);
        }
        final JTextField textField = (JTextField) nicCombo.getEditor().getEditorComponent();
        String a = textField.getText();
        ArrayList<Customer> customerlist = null;
        if (!a.isEmpty()) {
            try {
                customerlist = CustomerController.searchCustomerByNic(a);
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
            }
            Customer[] customer = new Customer[customerlist.size()];
            for (int i = 0; i < customerlist.size(); i++) {
                customer[i] = customerlist.get(i);
            }
            try {
                if (customerlist.size() == 1 && customer != null) {
                    customerCombo.getEditor().setItem(customer[0].getCustName());
                    custIdText.setText(customer[0].getCustId());
                    addressText.setText(customer[0].getAddress());
                    custEmailText.setText(customer[0].getCustEmail());
                    telText.setText(Integer.toString(customer[0].getTel()));
                    int a1 = customerTable.getRowCount();
                    int b = 0;
                    String text2 = custIdText.getText();
                    for (int i = 0; i < a1; i++) {
                        if (customerTable.getValueAt(i, 0).toString().equals(text2)) {

                            break;
                        } else {
                            b++;
                        }
                    }

                    ListSelectionModel selectionModel = customerTable.getSelectionModel();
                    selectionModel.setSelectionInterval(0, b);
                } else if (customer != null) {
                    customerCombo.getEditor().setItem(customer[0].getCustName());
                    custIdText.setText(customer[0].getCustId());
                    addressText.setText(customer[0].getAddress());
                    custEmailText.setText(customer[0].getCustEmail());
                    telText.setText(Integer.toString(customer[0].getTel()));
                    int a1 = customerTable.getRowCount();
                    int b = 0;
                    String text3 = custIdText.getText();
                    for (int i = 0; i < a1; i++) {
                        if (customerTable.getValueAt(i, 0).toString().equals(text3)) {

                            break;
                        } else {
                            b++;
                        }
                    }

                    ListSelectionModel selectionModel = customerTable.getSelectionModel();
                    selectionModel.setSelectionInterval(0, b);
                }
            } catch (Exception e) {

            }

        }
    }//GEN-LAST:event_nicComboActionPerformed

    private void addcancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcancelButtonActionPerformed

        addcancelButton.setVisible(false);
        nicCombo.removeAllItems();
        addButton.setEnabled(false);
        custIdText.setText("");
        nicCombo.addItem("");
        addressText.setText("");
        custEmailText.setText("");
        telText.setText("");
        nicCombo.addItem("");
//        addressText.setEditable(false);
//        custEmailText.setEditable(false);
//        telText.setEditable(false);
        //nicCombo.setEditable(false);
        customerCombo.removeAllItems();
        customerCombo.setEnabled(true);
        ArrayList<Customer> customerList = null;
        try {
            customerList = CustomerController.getAllCustomer();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
        }
        for (Customer customer : customerList) {
            customerCombo.addItem(customer.getCustName());
            new ComboSearch().setSearchableComboBox(customerCombo, "No Customer Found..");
        }
    }//GEN-LAST:event_addcancelButtonActionPerformed

    private void nicComboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicComboKeyReleased
        checkTextBoxes();
        final JTextField text1 = (JTextField) nicCombo.getEditor().getEditorComponent();
        String text = (String) text1.getText();
        if (text.length() > 0) {
            if (text.matches("[0-9]{9}[vV]")) {
                nicCombo.setForeground(Color.BLACK);
                nicc.setVisible(false);
            } else {
                nicCombo.setForeground(Color.red);
                nicc.setVisible(true);
            }
        } else {
            nicCombo.setForeground(Color.BLACK);
            nicc.setVisible(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_nicComboKeyReleased

    private void customerTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseReleased
        DefaultTableModel dtm2 = (DefaultTableModel) customerTable.getModel();
        int a = customerTable.getSelectedRow();
        String a2 = (String) dtm2.getValueAt(a, 0);
        Customer customer = null;
        try {
            customer = CustomerController.searchCustomer(a2);
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(ViewCustomer.this, e.getMessage());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(ViewCustomer.this, e.getMessage());
        }
        if (customer != null) {
            custIdText.setText(customer.getCustId());
            custEmailText.setText(customer.getCustEmail());
            addressText.setText(customer.getAddress());
            telText.setText(Integer.toString(customer.getTel()));
            nicCombo.getEditor().setItem(customer.getNic());
            customerCombo.getEditor().setItem(customer.getCustName());
        }
    }//GEN-LAST:event_customerTableMouseReleased

    private void customerTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerTableKeyReleased
        DefaultTableModel dtm2 = (DefaultTableModel) customerTable.getModel();
        int a = customerTable.getSelectedRow();
        String a2 = (String) dtm2.getValueAt(a, 0);
        Customer customer = null;
        try {
            customer = CustomerController.searchCustomer(a2);
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(ViewCustomer.this, e.getMessage());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(ViewCustomer.this, e.getMessage());
        }
        if (customer != null) {
            custIdText.setText(customer.getCustId());
            custEmailText.setText(customer.getCustEmail());
            addressText.setText(customer.getAddress());
            telText.setText(Integer.toString(customer.getTel()));
            nicCombo.getEditor().setItem(customer.getNic());
            customerCombo.getEditor().setItem(customer.getCustName());
        }
    }//GEN-LAST:event_customerTableKeyReleased

    private void customerTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerTableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerTableKeyPressed

    private void custIdTextPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_custIdTextPropertyChange


    }//GEN-LAST:event_custIdTextPropertyChange

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String id = customerTable.getValueAt(customerTable.getSelectedRow(), 0).toString();
        int a;
        try {
            a = CustomerController.deleteCustomer(id);
            if (a > 0) {
                JOptionPane.showMessageDialog(ViewCustomer.this, "Deleted.");
                ArrayList<Customer> customerList = null;
                try {
                    customerList = CustomerController.getAllCustomer();
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
                }
                DefaultTableModel dtm = (DefaultTableModel) customerTable.getModel();
                dtm.setRowCount(0);
                customerCombo.removeAllItems();
                for (Customer customer : customerList) {
                    customerCombo.addItem(customer.getCustName());
                    Object[] rowData = {customer.getCustId(), customer.getNic(), customer.getCustName(), customer.getTel(), customer.getCustEmail(), customer.getAddress()};
                    dtm.addRow(rowData);
                    new ComboSearch().setSearchableComboBox(customerCombo, "No Customer Found..");
                }
                ListSelectionModel selectionModel = customerTable.getSelectionModel();
                selectionModel.setSelectionInterval(0, 0);
            } else {
                JOptionPane.showMessageDialog(ViewCustomer.this, "Deleting Error");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
        }


    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        Customer customeru = null;
        try {
            customeru = new Customer(custIdText.getText(), customerCombo.getEditor().getItem().toString(), nicCombo.getEditor().getItem().toString(), addressText.getText(), custEmailText.getText(), Integer.parseInt(telText.getText()));

            try {
                int a = CustomerController.updateCustomer(customeru);
                if (a > 0) {
                    JOptionPane.showMessageDialog(ViewCustomer.this, "Updated.");
                    ArrayList<Customer> customerList = null;
                    try {
                        customerList = CustomerController.getAllCustomer();
                    } catch (ClassNotFoundException ex) {
                        JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
                    }
                    DefaultTableModel dtm = (DefaultTableModel) customerTable.getModel();
                    dtm.setRowCount(0);
                    customerCombo.removeAllItems();
                    for (Customer customer : customerList) {
                        customerCombo.addItem(customer.getCustName());
                        Object[] rowData = {customer.getCustId(), customer.getNic(), customer.getCustName(), customer.getTel(), customer.getCustEmail(), customer.getAddress()};
                        dtm.addRow(rowData);
                        new ComboSearch().setSearchableComboBox(customerCombo, "No Customer Found..");
                    }
                    ListSelectionModel selectionModel = customerTable.getSelectionModel();
                    selectionModel.setSelectionInterval(0, 0);
                } else {
                    JOptionPane.showMessageDialog(ViewCustomer.this, "Updating Error");
                }
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(ViewCustomer.this, ex.getMessage());
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(ViewCustomer.this, "Fields are not valid ");
        }

    }//GEN-LAST:event_updateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addcancelButton;
    private javax.swing.JTextField addressText;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel custCountText;
    private javax.swing.JTextField custEmailText;
    private javax.swing.JTextField custIdText;
    private javax.swing.JComboBox customerCombo;
    private javax.swing.JTable customerTable;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newButton;
    private javax.swing.JComboBox nicCombo;
    private javax.swing.JLabel nicc;
    private javax.swing.JTextField telText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
