/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PCHardwareSpecialists.view;

import PCHardwareSpecialists.controller.BrandItemDetailsController;
import PCHardwareSpecialists.controller.IdGen;
import PCHardwareSpecialists.controller.ItemController;
import PCHardwareSpecialists.controller.SupplierController;
import PCHardwareSpecialists.model.BrandItemDetails;
import PCHardwareSpecialists.model.Item;
import PCHardwareSpecialists.model.Supplier;
import PCHardwareSpecialists.view.NewItem;
import PCHardwareSpecialists.view.ViewItems;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hasithakn
 */
public class ViewSupplier extends javax.swing.JInternalFrame {

    NewSupplyOrder nso = null;

    /**
     * Creates new form ViewCustomer
     */
    public ViewSupplier() {
        initComponents();
        fillSupplierCombo();
        fillSuppliersTable();
    }

    public ViewSupplier(NewSupplyOrder a) {
        nso = a;
        initComponents();
        fillSupplierCombo();
        fillSuppliersTable();
    }

    public void supIdGen() {
        try {
            supplierIdText.setText(IdGen.getNextId("supplier", "supId", "S"));
        } catch (Exception ex) {
            Logger.getLogger(NewItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public boolean checkBeforeAdd() {
        ArrayList<Supplier> supplierList = null;
        try {
            supplierList = SupplierController.searchSupplierByName(supplierNameText.getText());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(ViewSupplier.this, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(ViewSupplier.this, ex.getMessage());
        }
        if (supplierList.size() > 0) {
            return true;
        } else {
            return false;
        }
    }

    public void fillSuppliersTable() {
        ArrayList<Supplier> supplierList = null;
        try {
            supplierList = SupplierController.getAllSupplier();

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(ViewSupplier.this, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(ViewSupplier.this, ex.getMessage());
        }
        DefaultTableModel dtm = (DefaultTableModel) supplierTable.getModel();
        dtm.setRowCount(0);
        for (Supplier supplier : supplierList) {
            Object[] rowData = {supplier.getSupId(), supplier.getSupName()};
            dtm.addRow(rowData);
        }

    }

    public void fillSupplierCombo() {
        ArrayList<Supplier> supplier = null;
        try {
            supplier = SupplierController.getAllSupplier();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(ViewSupplier.this, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(ViewSupplier.this, ex.getMessage());
        }
        supplierCombo.removeAllItems();
        for (Supplier supplier1 : supplier) {
            supplierCombo.addItem(supplier1.getSupName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        supplierTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        supplierIdText = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        supplierCombo = new javax.swing.JComboBox();
        supplierNameText = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Supplier");

        supplierTable.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        supplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Supplier "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        supplierTable.getTableHeader().setReorderingAllowed(false);
        supplierTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                supplierTableMouseReleased(evt);
            }
        });
        supplierTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supplierTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(supplierTable);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Supplier Details"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Supplier ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Supplier Name");

        supplierIdText.setEditable(false);
        supplierIdText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        addButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        addButton.setText("ADD New");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        supplierCombo.setEditable(true);
        supplierCombo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        supplierNameText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        supplierNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supplierNameTextKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supplierCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(supplierNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(supplierIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addButton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(supplierCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(supplierIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton)))
        );

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        deleteButton.setText("Delete Selected");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        updateButton.setText("Update Selected");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(deleteButton)
                    .addComponent(updateButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (!checkBeforeAdd()) {
            if (!supplierNameText.getText().isEmpty()) {
                supIdGen();
                Supplier supplier = new Supplier(supplierIdText.getText(), supplierNameText.getText());
                try {
                    int a = SupplierController.addSupplier(supplier);
                    if (a > 0) {
                        JOptionPane.showMessageDialog(ViewSupplier.this, "Supplier Added");

                        if (nso != null) {
                            nso.fillSupplierCombo();
                            nso.fillSupplierDetailsByName();
                            nso.supplierCombo.getEditor().setItem(supplier.getSupName().toString());
                            nso.supIdText.setText(supplier.getSupId());
                        }

                        fillSupplierCombo();
                        fillSuppliersTable();
                    } else {
                        JOptionPane.showMessageDialog(ViewSupplier.this, "Supplier Adding Failed");
                    }
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(ViewSupplier.this, ex.getMessage());
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(ViewSupplier.this, ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(ViewSupplier.this, "Supplier Name Field Is Empty");
            }
        } else {
            JOptionPane.showMessageDialog(ViewSupplier.this, "Supplier Name " + supplierNameText.getText() + " Already Added");
        }


    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void supplierNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierNameTextKeyReleased
        //supplierIdText.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_supplierNameTextKeyReleased

    private void supplierTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierTableMouseReleased
        String supId = supplierTable.getValueAt(supplierTable.getSelectedRow(), 0).toString();
        Supplier supplier = null;
        try {
            supplier = SupplierController.searchSupplier(supId);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(ViewSupplier.this, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(ViewSupplier.this, ex.getMessage());
        }
        if (supplier != null) {
            supplierIdText.setText(supplier.getSupId());
            supplierNameText.setText(supplier.getSupName());
        } else {
            supplierIdText.setText("");
            supplierNameText.setText("");
        }
    }//GEN-LAST:event_supplierTableMouseReleased

    private void supplierTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierTableKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String supId = supplierTable.getValueAt(supplierTable.getSelectedRow(), 0).toString();
            Supplier supplier = null;
            try {
                supplier = SupplierController.searchSupplier(supId);
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(ViewSupplier.this, ex.getMessage());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(ViewSupplier.this, ex.getMessage());
            }
            if (supplier != null) {
                supplierIdText.setText(supplier.getSupId());
                supplierNameText.setText(supplier.getSupName());
            } else {
                supplierIdText.setText("");
                supplierNameText.setText("");
            }        // TODO add your handling code here:
        }

    }//GEN-LAST:event_supplierTableKeyReleased

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            String supId = supplierTable.getValueAt(supplierTable.getSelectedRow(), 0).toString();
            try {
                int a = SupplierController.deleteSupplier(supId);
                if (a > 0) {
                    JOptionPane.showMessageDialog(ViewSupplier.this, "Supplier Deleted");
                    if (nso != null) {
                        nso.fillSupplierCombo();
                        nso.fillSupplierDetailsByName();
                        nso.supIdText.setText("");
                    }
                    fillSuppliersTable();
                    fillSupplierCombo();
                    supplierIdText.setText("");
                    supplierNameText.setText("");
                } else {
                    JOptionPane.showMessageDialog(ViewSupplier.this, "Supplier Not Deleted");
                }
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(ViewSupplier.this, ex.getMessage());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(ViewSupplier.this, ex.getMessage());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(ViewSupplier.this, "Please Select Supplier Before Delete");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        if (!checkBeforeAdd()) {
            if (!supplierNameText.getText().isEmpty()) {
                Supplier supplier = new Supplier(supplierTable.getValueAt(supplierTable.getSelectedRow(), 0).toString(), supplierNameText.getText());
                try {
                    int a = SupplierController.updateSupplier(supplier);
                    if (a > 0) {
                        JOptionPane.showMessageDialog(ViewSupplier.this, "Supplier Updated");
                        if (nso != null) {
                            nso.fillSupplierCombo();
                            nso.fillSupplierDetailsByName();
                            nso.supIdText.setText("");
                        } else {
                        }

                        fillSupplierCombo();
                        fillSuppliersTable();
                    } else {
                        JOptionPane.showMessageDialog(ViewSupplier.this, "Supplier Updating Failed");
                    }
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(ViewSupplier.this, ex.getMessage());
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(ViewSupplier.this, ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(ViewSupplier.this, "Supplier Name Field Is Empty");
            }
        } else {
            JOptionPane.showMessageDialog(ViewSupplier.this, "Supplier Name " + supplierNameText.getText() + " Already Updated");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox supplierCombo;
    private javax.swing.JTextField supplierIdText;
    private javax.swing.JTextField supplierNameText;
    private javax.swing.JTable supplierTable;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
